# Syslog发送工具配置文件

# 基础配置
target: "localhost:514"          # 目标Syslog服务器地址
source_ip: ""                    # 源IP地址，留空表示自动
protocol: "udp"                  # 传输协议: udp/tcp

# Syslog配置
format: "rfc3164"                # Syslog格式: rfc3164/rfc5424
facility: 16                     # Facility值 (16=local0)
severity: 6                      # Severity值 (6=info)

# 发送控制
eps: 10                          # 每秒事件数
duration: "60s"                  # 发送持续时间
concurrency: 1                   # 并发连接数
retry_count: 3                   # 重试次数
timeout: "5s"                    # 连接超时
buffer_size: 1000                # 缓冲区大小

# 数据源配置
template_dir: "./data/templates" # 模板目录
template_file: ""                # 指定模板文件
data_file: ""                    # 数据文件

# 监控配置
enable_stats: true               # 启用统计
stats_interval: "5s"             # 统计间隔

# 示例配置场景
# 
# 1. 高速发送测试:
#    eps: 1000
#    duration: "30s"
#    concurrency: 5
#
# 2. 长时间稳定发送:
#    eps: 50
#    duration: "1h"
#    concurrency: 2
#
# 3. 安全日志模拟:
#    template_dir: "./data/templates/security"
#    facility: 4  # auth
#    severity: 4  # warning
#
# 4. 系统日志模拟:
#    template_dir: "./data/templates/system"
#    facility: 0  # kernel
#    severity: 3  # err