name: Release Package

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: '发布版本号（例如：1.0.0）'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set version
        shell: bash
        id: set_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.inputs.version || '0.0.1' }}" >> $GITHUB_ENV
          fi

      - name: Build all platforms
        shell: bash
        run: |
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o syslog_go-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o syslog_go-windows-arm64.exe

          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o syslog_go-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o syslog_go-linux-arm64

          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o syslog_go-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o syslog_go-darwin-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: syslog_go-binaries
          path: syslog_go-*

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: syslog_go-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}