name: Release RPM Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install RPM build tools and Go
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          # 添加Go仓库
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install -y golang-1.20

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build RPM package
        run: |
          # 创建rpmbuild目录结构
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          
          # 创建源码包
          tar czf ~/rpmbuild/SOURCES/syslog_go-${VERSION}.tar.gz .
          
          # 更新spec文件版本
          sed -i "s/Version:.*/Version:        ${VERSION}/" syslog_go.spec
          
          # 复制spec文件
          cp syslog_go.spec ~/rpmbuild/SPECS/
          
          # 构建RPM包
          rpmbuild -ba ~/rpmbuild/SPECS/syslog_go.spec

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/rpmbuild/RPMS/x86_64/syslog_go-*.rpm
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}